server:
    port: 8084

spring:
    application: 
        name: collab-service
    kafka: 
        bootstrap-servers: localhost:9092
        consumer:
            group-id: collab-sync-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "com.aeternus.note_service.model"
        
    redis:
        host: localhost
        port: 6379
app:
    jwt:
        secret: SessionTokenCreatedBySecret22222222222222222222222222222222222222
